on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build:
    permissions:
      contents: write
    name: Build Mkosi Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: Install build deps
        run: |
          sudo apt -y update
          sudo apt -y install make debootstrap mtools python3-pefile
      - name: setup-mkosi
        uses: systemd/mkosi@v26
      - name: Build Artifacts
        working-directory: mkosi
        run: |
          make -j$(nproc) IMAGE_VERSION=$(echo $GITHUB_REF_NAME | tr -d 'v')
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            mkosi/mkosi.output/*.raw
